apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: meroppfolging-frontend
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name: team-esyfo
  secretName: meroppfolging-frontend-unleash-secrets
  environment: production
