apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: {{appname}}-demo
  namespace: team-esyfo
  labels:
    team: team-esyfo
    branchState: {{branchState}}
spec:
  image: {{image}}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 3000
  tokenx:
    enabled: false
  idporten:
    enabled: false
    sidecar:
      enabled: false
  liveness:
    path: syk/meroppfolging/api/isAlive
    initialDelay: 20
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: syk/meroppfolging/api/isReady
    initialDelay: 20
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: actuator/metrics
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  ingresses:
    - {{ingress}}
  env:
    - name: VEIARBLREGISTRERING_START_REGISTRATION_API_URL
      value: http://veilarbregistrering.paw/veilarbregistrering/api/startregistrering/
    - name: VEIARBLREGISTRERING_COMPLETE_REGISTRATION_API_URL
      value: http://veilarbregistrering.paw/veilarbregistrering/api/fullfoersykmeldtregistrering/
    - name: ESYFOVARSEL_MAX_DATE_API_URL
      value: https://esyfovarsel.dev.intern.nav.no
  accessPolicy:
    outbound:
      rules:
        - application: nav-dekoratoren
          namespace: personbruker
