apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: meroppfolging-frontend
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{image}}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  port: 3000
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
  liveness:
    path: syk/mer-oppfolging/api/isAlive
    initialDelay: 20
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: syk/mer-oppfolging/api/isReady
    initialDelay: 20
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: actuator/metrics
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  ingresses:
    - 'https://www.ekstern.dev.nav.no/syk/mer-oppfolging-wip'
  env:
    - name: DECORATOR_ENV
      value: 'dev'
    - name: RUNTIME_ENVIRONMENT
      value: dev
  accessPolicy:
    outbound:
      rules:
        - application: nav-dekoratoren
          namespace: personbruker
