apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: meroppfolging-frontend
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{image}}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  port: 3000
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level4
  liveness:
    path: syk/meroppfolging/api/isAlive
    initialDelay: 20
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: syk/meroppfolging/api/isReady
    initialDelay: 20
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: actuator/metrics
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  ingresses:
    - 'https://www.ekstern.dev.nav.no/syk/meroppfolging'
  env:
    - name: ESYFOVARSEL_MAX_DATE_API_URL
      value: http://esyfovarsel/api/v1/sykepenger/maxdate
    - name: SYKEPENGEDAGER_INFORMASJON_MAX_DATE_API_URL
      value: http://sykepengedager-informasjon/api/v1/sykepenger/maxdate
    - name: MEROPPFOLGING_BACKEND_URL
      value: http://meroppfolging-backend
  envFrom:
    - secret: meroppfolging-frontend-unleash-secrets
  accessPolicy:
    outbound:
      rules:
        - application: nav-dekoratoren
          namespace: personbruker
        - application: esyfovarsel
        - application: meroppfolging-backend
        - application: sykepengedager-informasjon
      external:
        - host: team-esyfo-unleash-api.nav.cloud.nais.io
