name: Deploy redirect ingress to dev
on:
  push:
    paths:
      - 'nais/redirect-dev.yaml'
      - '.github/workflows/deploy-redirect**'
    branches:
      - '**'
jobs:
  deploy:
    name: deploy redirect ingress to dev
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Deploy redirect ingress to dev-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais/redirect-dev.yaml
